	.section	.text,"ax",@progbits
	.assume	adl = 1
	.section	.text,"ax",@progbits
	.global	_realloc
_realloc:
	ld	hl, -3
	call	__frameset
	ld	iy, (ix + 6)
	lea	hl, iy+0
	add	hl, bc
	or	a, a
	sbc	hl, bc
	jr	nz, BB0_2
	ld	hl, (ix + 9)
	push	hl
	call	_malloc
	push	hl
	pop	bc
	jr	BB0_6
BB0_2:
	ld	de, 6
	ld	hl, (iy - 3)
	lea	bc, iy+0
	ld	iy, (ix + 9)
	add	iy, de
	lea	de, iy+0
	or	a, a
	sbc	hl, de
	jr	nc, BB0_7
	ld	hl, (ix + 9)
	push	hl
	call	_malloc
	push	hl
	pop	de
	pop	hl
	push	de
	pop	hl
	add	hl, bc
	or	a, a
	sbc	hl, bc
	jr	nz, BB0_5
	ld	bc, 0
	jr	BB0_7
BB0_5:
	ld	hl, (ix + 9)
	push	hl
	ld	hl, (ix + 6)
	push	hl
	push	de
	ld	(ix - 3), de
	call	_memcpy
	pop	hl
	pop	hl
	pop	hl
	ld	hl, (ix + 6)
	push	hl
	call	_free
	ld	bc, (ix - 3)
BB0_6:
	pop	hl
BB0_7:
	push	bc
	pop	hl
	ld	sp, ix
	pop	ix
	ret
	.section	.text,"ax",@progbits

	.extern	__frameset
	.extern	_malloc
	.extern	_free
	.extern	_memcpy
